source:
  urls:
    - "https://example.com/announcements.yaml"
    - "file:///path/to/local/announcements.yaml"

worker:
  lookback_period: 24h

git:
  auth:
    github.com:
      username: ""
      token: ""

slack:
  app:
    token: ""
